<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

        <h1>Advance JavaScript - Error Handling Tutorial</h1>
            <p>
                In this tutorial you will learn javascript error handling & try catch tutorial.You can
                learn how to catch errors with javascript try cath method exceptional handling.
            </p>

            <img src="Screenshot_1.jpg" alt="">

            <h2>Different type of Error in JavaScript</h2>
            <img src="Screenshot_2.jpg" alt="">

            <ol>
                <li>EvalError </li>
                <li>RangeError </li>
                <li>ReferenceError </li>
                <li>SyntaxError </li>
                <li>TypeError </li>
                <li>URIError </li>
                <li>AggregateError
                    <p>will show in promise</p>
                </li>
            </ol>




            <!-- <script>
                blabal;

            </script> -->








            <!-- <script>
                try{
                    console.log("Start of Try");

                    blabla();

                    console.log("End of Try");
                }catch(error) {
                    console.log("Error has Occurred");
                }
            </script> -->
            
            
            

            
            
            
            

                    <!-- error on which line  -->
            <!-- <script>
                try{
                    console.log("Start of Try");

                    blabla();

                    console.log("End of Try");
                }catch(error) {
                    console.log(error);
                }
            </script> -->
            
            
            
            
            
                    <!-- use try catch inside setTimeout Function -->
            <!-- <script>
                setTimeout(function(){
                    try{
                        blabla;
                    }catch(error){
                        console.log("error has occurred");
                    }
                }, 1000);

            </script> -->
            
            
            
            
            
            
            
            
            
            
            
            

            <!-- <script>
                    try{
                        blabla;
                    }catch(error){
                        // console.log("error has occurred");
                        // console.log(error);

                        console.log(error.name);
                        console.log(error.message);
                        console.log(error.stack);
                    };

            </script> -->









</body>
</html>